server:
  port: 8081
  servlet:
    context-path: /
debug: true
spring:
  profiles:
    active: default
  sql:
    init:
      mode: always
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
minerva:
  auth-header: x-minerva
