server:
  port: 8081
  servlet:
    context-path: /
debug: true
spring:
  profiles:
    active: default
  sql:
    init:
      mode: always
  datasource:
    url: "jdbc:sqlite:sqlitesample.db"
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
minerva:
  keyvalue:
    encrypt: false
    encryption-key: "1234567890123456"
