---
minerva:
    hash:
        argon2:
            bring-your-own-salt: vQlm0mVHOcpEiEYI3GEYxw==
    encryption:
        gnupg:
            armored-public-key: |+
                -----BEGIN PGP PUBLIC KEY BLOCK-----

                mDMEZa70ABYJKwYBBAHaRw8BAQdAqc7Zfp6aQyefH7FWJOHWGyKSwIZe2L9e+pVm
                umnaeIy0LG1pbmVydmEtdGVzdCA8bWluZXJ2YS10ZXN0QG1pbmVydmEtdGVzdC5j
                b20+iJkEExYKAEEWIQR/tX7WJd7W0WbxhY/rY/cBPZC6AAUCZa70AAIbAwUJBaOa
                gAULCQgHAgIiAgYVCgkICwIEFgIDAQIeBwIXgAAKCRDrY/cBPZC6AP0OAQCnWQJg
                EDHdRIugMORCBLo9i7gTnTNgV3ov9n3h+yMPmgD9HN29m9o0OIQbDyFCqE4jwbU0
                UDB6/aX2dgXgwF0xagC4OARlrvQAEgorBgEEAZdVAQUBAQdAemolmqy4kFq5iEtF
                ZyEELwf73OY7DcWFK5NIv0xCz18DAQgHiH4EGBYKACYWIQR/tX7WJd7W0WbxhY/r
                Y/cBPZC6AAUCZa70AAIbDAUJBaOagAAKCRDrY/cBPZC6AJ8eAP4qOtZ535X89wei
                q3J5c9sV9jopcu6BJtXrXhk23W3fhgD/fAbW3Daqa2mNLLYSkLH06b6+tjpOxsd2
                /aPa84R3hAw=
                =kgso
                -----END PGP PUBLIC KEY BLOCK-----

            armored-private-key: |+
                -----BEGIN PGP PRIVATE KEY BLOCK-----

                lIYEZa70ABYJKwYBBAHaRw8BAQdAqc7Zfp6aQyefH7FWJOHWGyKSwIZe2L9e+pVm
                umnaeIz+BwMCdNs9UHB91Gn/sq1FqE2sz9/ZguQjtGCOsmqjAUr5WJqGB2NE9RR4
                2GgMEWy5UzDZzcO5ckHEZVuqE0HbAH/X2Farkr6ZBIDDWeLNs2CqBbQsbWluZXJ2
                YS10ZXN0IDxtaW5lcnZhLXRlc3RAbWluZXJ2YS10ZXN0LmNvbT6ImQQTFgoAQRYh
                BH+1ftYl3tbRZvGFj+tj9wE9kLoABQJlrvQAAhsDBQkFo5qABQsJCAcCAiICBhUK
                CQgLAgQWAgMBAh4HAheAAAoJEOtj9wE9kLoA/Q4BAKdZAmAQMd1Ei6Aw5EIEuj2L
                uBOdM2BXei/2feH7Iw+aAP0c3b2b2jQ4hBsPIUKoTiPBtTRQMHr9pfZ2BeDAXTFq
                AJyLBGWu9AASCisGAQQBl1UBBQEBB0B6aiWarLiQWrmIS0VnIQQvB/vc5jsNxYUr
                k0i/TELPXwMBCAf+BwMCizbuwMKSJ0n/reXH0dlE03diLm6k8irQt4aoEf5Fr3GO
                uxzWPcrRJJqtwC/I5f4UplVmF3tz5/t2xahIr6nED8kzdk21qQSY5jmnIunMMIh+
                BBgWCgAmFiEEf7V+1iXe1tFm8YWP62P3AT2QugAFAmWu9AACGwwFCQWjmoAACgkQ
                62P3AT2QugCfHgD+KjrWed+V/PcHoqtyeXPbFfY6KXLugSbV614ZNt1t34YA/3wG
                1tw2qmtpjSy2EpCx9Om+vrY6TsbHdv2j2vOEd4QM
                =SQ4t
                -----END PGP PRIVATE KEY BLOCK-----

            private-key-passphrase: password
    physical:
        key-value-persistence:
            persistence-type: file
        key-value-file-storage:
            path: /tmp/minerva
    pki:
        openssl:
            ca-private-key-passphrase: TyBb1SbqcZ4em4q2hQstLcWITKmMxAxo3YHRChenbM8EROsKSo2hPWKZbzpawxiF
            ca-private-key: |+
                -----BEGIN ENCRYPTED PRIVATE KEY-----
                MIIStTBfBgkqhkiG9w0BBQ0wUjAxBgkqhkiG9w0BBQwwJAQQyfpTt0VZPBjnl5Mk
                mxHbjQICCAAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEJBWc1hpvhun88qy
                Axfpo4YEghJQMTrruuB/az0IJGqiQkU6ZLHosXW/TxBWqkslDpxqm5euvRk706f4
                epVU1WKkUyWZQKlTOwjv2qfR7g/P8e+2DAb3mwrWrIHklYI/57OeFg4NIDgDtiYC
                dfgAnoILDJpepO/+416mFUEuSmQTyTdLp4UW1Cu/lYqDW0UXRA4KktIhJndGQ6zF
                u3IfPxTyJR/4FXRi7YXnUj66w9f7f15ZhYQFhTcWLJUmcyz6ebcX0iN5vLWKGODX
                LDNclyiKJ4AWsoSX90ows2MIQLnQl9nGa/OFO4AWhtsewWSfKbOFBw8dhw3LUgV+
                yLG1CQpMDQyh6jIl8Ivx9vEWEb04Sw/Q51NdNdxfaw0wUOeMdv1NGnX28E+qEeGO
                FpNKWiQ0us42hf8v6NscoQ35+fxh3YhgzjXwyHJCJcwdKkENuFM+cQc7METwsH0/
                5KIzrqsTnwy4LTKvaCb3yqQRlXjaRnxynL+BCpMXjteCYn1ZMFjwjZLxzEt5yHUT
                H9qi3V/IcYYy2/yctW9VbrBkfHve7SrwQExewEBlugSahXv25rEg8l20Rw6q5+hl
                a4nzCQPVceD5tHk+ByCPg5W7Hl02PrVeixeNM6Cc5P9TWPuePu1kssZrqc7TeiMb
                OC3n3OeTL+Z6ybhAE183rbkP+fm+8xb7DH0vLvTOcmjMV+EzSaPTrvYWJQ9WB1m8
                KUOlMtH+vj3ZI06l+BLBCpoqzBTxKYzcPZwoOFC3gnyX3lIcMiHY9Z/s0tIJr0fQ
                K3mdmm8moxNAeqG8g545oOEPN+f9kUlM34QXJ1NASlpmwGr+XGtPc/zZp5UQoEAt
                ThM8fqmouF3eGwWMS/mWymnX0ARrqOcB6uEQAIZdx7yJYrkgEPIILFQjCS9L1YZ4
                AY4SGKPOYCwCtWH1EQu7posbtiajXzrqO9pmJ4slce9IMN1AxgwvYHqolatCFtNt
                fEP2K3igaXn1OpeRnMpAcFmG+6LaQHETDTjHYuMVKhBYWlWiFpxB80FCBH1Pxmtj
                Xgei7mmdIxKsLPv0gQAWYtfmbzqU5Suz0yVcbabCYgkh+LBhXrOEhb6En872ULeC
                6zZdTtIR/ktyM7jc5LIgWHsQ8t8aUPpWfkUO+FGKUl6C3SSM4twiR8oqYhPZEuR/
                9X0dHK08PPppw7qwanpHm4AxQ/lEKgXGsrScciRGTFVoTZbw6c6VhhLi3NQDoEqm
                8znfUz+mFDRGBglWYi3Q8gViN1DvKcyJA231qyz2ZtmAOm8kYmB26ydDiIRB5KQL
                bdF5c86eexaqEHMTITzs1SH37uo4OLd8gYD027bz13OfHwGVOkmu6wtTtkw8gfSY
                nGnlT1CLty8Fff4Xyg9PTu5wb41oN1xM0tOQ2AP7BgVPbPmJI6lOckbjv6v04sqJ
                OfK70SUwirrmnKwnyBx3PaTXSlhoNvIIFlQVywB47phXgVFiJ/znVXMyUAjB8mel
                30x4tZR9AbP0UNFEx3IhjxW7XcsWATmL1EpggBWC1Q6fpg6csOmcLxsOGFQqJ/Pl
                Y8iqDeKQb6ssqScgKn3kALzR+DwHPrXtghc/gcO9BxGiPJNK/Lo1xQpO/xz0TIbB
                SeJsCCP89qBPDkC+sc6hAW/3HDU9aAb+cPSrrIwiwi5IsFyQPV7Sra4X9IYFyv/9
                L/jeKm8QVaSZU07rFiMmrAhzuRpwY69gMm1DlSBNfe6bcWIKVEmdB4nRiOrhZtJ1
                QW7Y3mV9FgZZEsrKnmpQhhDElJieYWywL0AeNObZ+Nb4GYB6exq0Y5D3Slv+KTTx
                7v+MMtbXpKRSCJhAPJTuwnlvh1CwC3pmWk3bSJ6tBGGkIETtkeWR6kuDi8eoshBA
                +fx1wyZlFGUSNIn3W6dE/5DlUsfzeplTFVov5+wdjl7iBcQufXiSGrqLWhjqzizv
                820XLD3fT8W8yITF8UWSlWHEO4KcdEPr+pIGkUj04fqUZKqOZFAfNRlJ6RYoTOq9
                xS8VLETH9v+Kr6uY9guV/jh5b5bQTbFZcI4x3fBjzYUjkCq8UsJ8jMhA2l9aUK7x
                UOn7AfRXUtVnDes+5Y/wrMKV65GQTknQ6aEXjnPlxphCbrC9fqSfNLgVnQrNeHyR
                v/+oIxYulpRGuqsufo2Ej9pksI4BZPbNsgdbnDEfLWfzadBYocIEJzFw5wGBGnIO
                tEDrrKEuGZGeCKFjbUCOu62GdYPaNltlkuDxJ/F9KMiBSYuUjRZgLtvxV7oJHq9w
                rezvoX6/uEPRX+GLqOi69efFrsJxPNby39+O+dCZZmVfRi8ii8q4kHiWQg/R+RKW
                vOK74iFw8jLd6FpOF3nk+diYTDbgFmN1Pm7z5wEGyPmNr8flOfVc8EZSU+I1YMFq
                KYYT3mW4LLPVSA/N0Cq27vGPHqS25pxu3xOZdMGguv6Do0oW2ezvy3aXzHjTiru7
                LPGZs38MtYoderCbm1yPpaGcXNr/Ne/EJz957XqFC+SMQnkt8Wi35NpiAhlXsr8t
                I/wmYPXNG12qBJ8Xc9Nbjo/W87SDEuAmqzY+vP29vpprKLYbUXvyxqn5VZ/lK1cR
                qDsFSfVR6pNzkZ9yN6aIeBG82iIRj8hIDptb8fXQXRH+eK3mN4ixyblEHMZVdm03
                RcpVm21T+sg+v0UD0WSx7SIVjyEa6hE7PkIxOkc7AN6iu7Nq/8+aHK9N3D9sp+lB
                Fwu0jUaB9V4s6nhzTvx3aNU97BO5SLEL8CJFLUlmftEcV2+cdKIRZdDmK3VzyNQ/
                TyHBogZE3JXwYYODyiROos0+tAiwMOXoAQG2g3QPwVjZ6byicQZikeBZeRaw8xGF
                QAC2b7/ZJSg2YJBduhR3UUNZiZTb9V78Y8R+RCljT6Qgwk2C7mwtMgKO+X30hSlD
                W29nWxdBImn6DOnj3pqAwYut8HbnGl6+9u1tuzPJIp5bWvv2p+g/BC9NT4PYH/cR
                38VSVkN/q70KnuiSbmDN1kOS6v0ofZRvf5uB1HR3krxtPFuK0dGavVVkE77E+iMH
                SGu3pYrzEmxcH4vKNfPabc655E4PufuwBDDgpj/E/1kF0ACp3iypFghS6koHBDzO
                CaQ+4IUdPg1JZ9uj6sOW+JLd1MI0iHkaAmIwJ2V3YyF2bBBeo32Lvvp4q9tsFHfO
                jZpBhjdPItZGn8019VWfYjX6p7/FRuHTWjcE506zKD7HSbuChcE6SJHV2ue1eYU9
                jSRNnz7STjoQXvB36Tnl9YiG6d3qqdy2GE86MefpxpV4KmZJet2PEZ0N4+FLtEfH
                Va8rvwUAfSdVbqKCagBN+zMs1Z8629DaKFXVuohmfZFofhe3YWwOFNIbI83vX81D
                feCmjqkd8Wqv7PYNywtjkDTi99TJz4/5FFSjBIV7Smp09VGNdosXlpm853FU2sSf
                tNAi6EsQa4zJkt+9GpiP9FiondUNTJyKn5/dXacOP/4ZvZ7fsIWTgWky6u7ggNBJ
                AUsAd+yRrvEXGZer8ZtDtsxqQINmb2rW+IE9SdhO5Jw4UVbw8CgAWCOIWD/6sxaJ
                lrq4x4mlM7n7Uu2+W6jvc3BB1y087IjY44JQfqlLEIrM5k0jBA3eAc/osWMLWE4c
                DttYghlwsXnP27jWcqcQ5Z1tcZizBn1kDuoBmITm2vCTSOZ7i0nYn92ed/JrIYBj
                qV6u2FWFSnwiBs4afqNmdhiMCptSTN45Io9numDGCqgGUNTmrScAr43OqSWXszzD
                NIiTpbvuB8dd2UHdC8H7L8bnT/sRj2YwWdiQOrXTHJHvTAyjQnfZMHwh8Kl/ENA1
                u6YzqmvBbweBUvF5VU7GwqOfLO2ngLs+VkzkhC2Tlq8O1k1LRNzybb3X8k+nsKHB
                dnOOq4fy7QPI2oRaNJTyJiCyhtzYH84MXauUT6r3/ou7qLaY8+NnvgA2KHJNIpiR
                5lxpIjKZO6SCGZx4rBKzuKLS/C6SxVfMGQOphn4XXc/TphIH92gr3QaveQxhbLhv
                NaOHXpNSRhSJQLWaa4Q0ur/6y8zlmafTxGJDlPeI7Vlu6CZhkglKJrGbEqY8rv3g
                jLlvLVJHZslKqdFXrJnfyjHP5iKIONCnAzMB3wMm21QjB7uvz1Gt9NoooD8vLCa9
                aIveGKotpHer1AyW/ot6oaUkyrNqYASl/drKYNBSvRyY8vY7p/i1YRQWNWyBHtAo
                HOE6j6Ct3O4fOMC41kisB+wV7DDTLTcBn/Ocuaq4j9QHkK2iJ/zhIa0JkJBviplG
                ms9QdJg8P9y0+jIY9A3q7bXER4HnNd+umumNeF/6b2FLuyxg2z041MQEzPTV4wA5
                xNjO5a6emz8su+N6QCL0prXiuj3c0jLWca8PUmBGlKtjUXWZGC4OsFwI+94dTR2D
                VPJAYnQRqqGnGVR3U4A/PrFJaduVS3b0Ytf9Q0pBpCbgA0I/WVY2M3CKCk4AG2xq
                3hzZq/CKyOy1oRVAk2JBULF7b1l/AWDEz0BhtICZJ4P5Lm6CK8ARll6CYsoUlhR3
                zVZQ0IlxdvKjoHRrdSdY7CDjrHXMHjFthre+CaJ1KXZ61xiKBk0CqKLM1DMejB18
                wKA4f4ze0+CiJ7tf7zBA7n7Hr+4CCZHXKxu5QJKQ0ZWW9dSfsDJ0MHlOWQVzaAQc
                WtAUS8Lmq83DWYSDJPn3rnRMvpNdGcapfSQEuiXtKcsP4vyM6D6mE15dO9SDuWy3
                A9H3RYLHClQTHbmonwvvpkIkrcAZ1DOnfAypRdSK4Sa2plT0pU/VnOn2x/T21JJ7
                p3lPHbg0RlsWPE5R69WnO7GDFu3i1qSIAmJleio3OOpuoZzpHOlwdT5/ibNuY5sn
                gq5dVDEb/H/Nwi4cm0C6h2OvUnsHPxlDsmwun77bz9EL3iPtf/N4kTJjlUc2Kzx1
                /FJ8Em3h9B2hy8J0ejE6b5Ij735ooImGPj9lGjqbHigNxtE/3dIJ28FqzeAad88J
                8KUE9aAgJiFNpYARa371a3fHzf8cheUeaMcBQNKWUSUarWnyof3SzerL+LjYSE9u
                KxWb+AKwsnyk8IP7JP4o1MkoD5Rc06Xsyx3YxVMbQCFi/jpVPCklDJ11L8TvzU0O
                1tDfyyZ93swGVfIuRF24PXkK6YqSjXY7OEXi5Uo4xA+MvDegN08fxUTLtpyA4g0b
                r2Jn7hVYzT941WKaCyJiZnkbtSAGt1HskMFdYf8Jpp/1ayEsvNX4H1NyOGzc0p9s
                S1Au9HakS8cel1BnUcBYnA0O2U+nngqSkWjBQIkJ65Bri4nyoQjK2sBYEP5dRhrf
                dH4bHBruD5wJPEL6YRy1jZXPgzAJi5aEYv7RiL9GOBXA8fGDP8NUoigMroeDvJeE
                sO5IT7aR5x166oUcsgz3thNYOHMLRFT01AZ0jtjhtKChZqg4MnJBAIUsqpgF6i1t
                tesfgTNWhoLm7HWHYd/DbJOV7waCQy96ssGLbX8jGGdemw7f9lKlVHma2sLI7beB
                2yN2e0AfpiTk5uLsIiAz1g+EMTEBwzOzmGGsho3xYdJFz2vPpI9cTqMj/rcRaZLh
                hX99Kjqr9nHSFBQfN+c3gw2lCKZF8gi57LvaVvQjs0ANCURxJhNe7Wrv//p032QM
                s7A2yGhxKjiUIFmAuPIr6bNqx6JRpjN9BX/FFUMDylxJMVdjDUnBuOCBHlTLxweI
                BgZNyoT8Py5EKqYTnISQfY6XX3CRyBtZd9CFgc0Q9oEOk6zIDmbs226vHEwm8JnI
                +JBCNtP553zjyAn451K1zodFxh26+0m9FF+S8jSVc5UlRlTCwmmyStl3vPzLolCN
                prKDMErumqA11OAF6POZ1mYCq1WTTsDwwTAn+Lk0NhKMny4OpBzaHdvsyprMtC8u
                iggGwTj9aZrZ7+wJUSsE19/e12t/zUlosMJn3dHxF3gvI++Tlzb2aSOD3I/09Pq3
                SmY29ofx1c2eRVKtkOJ4ZLlEG3o5dIX2YvzCf6YcJAZdmkvTUJ3iDstJ0Qurg56n
                AbKuhGhnXyla41V7Awqagon2wLmF2ySWDVGnt+f7U/aCg1oljVZVDPV7MT4fdNwd
                fGXbL4TM38BNfzuyqNaCB0oyS0cLb2u/AzF1pm1vfUVWiOp6PRUzOz+ytFaW0oWo
                mM4/oP1po5+pqEEEsq6lCd6Uwz0Gka2PZysCp4byt+mPFmIwume6IQBdlVS/AqkF
                6iiZf6SKRl5kkxzLIhnh2te8gaa3PMYWBSIYRiQZWx5Tc+TFHXkQWMM4vT7BIrA3
                sbeBw4SmxFzp/AyeduRagNif/XebM4bwh6P02qykDQWhZEv8MINBkTQ=
                -----END ENCRYPTED PRIVATE KEY-----

            ca-certificate: |+
                -----BEGIN CERTIFICATE-----
                MIIKLjCCBhagAwIBAgIUPrnN5VDuRy3zFScDHNmZccRFJoQwDQYJKoZIhvcNAQEL
                BQAwfTELMAkGA1UEBhMCSU4xFDASBgNVBAgMC1dlc3QgQmVuZ2FsMREwDwYDVQQH
                DAhBcmFtYmFnaDERMA8GA1UECgwIYXJwYW5yZWMxFDASBgNVBAsMC2FycGFucmVj
                IENBMRwwGgYDVQQDDBNhcnBhbnJlYyB0cnVzdGVkIENBMB4XDTI0MDExMjIyMjkx
                OVoXDTQ0MDEwNzIyMjkxOVowfTELMAkGA1UEBhMCSU4xFDASBgNVBAgMC1dlc3Qg
                QmVuZ2FsMREwDwYDVQQHDAhBcmFtYmFnaDERMA8GA1UECgwIYXJwYW5yZWMxFDAS
                BgNVBAsMC2FycGFucmVjIENBMRwwGgYDVQQDDBNhcnBhbnJlYyB0cnVzdGVkIENB
                MIIEIjANBgkqhkiG9w0BAQEFAAOCBA8AMIIECgKCBAEA4XSad6vOr7F5VfMmft+W
                uiczlvWNvxRruqIDdfQKQCwp3qWC2/waA4z2DmK5jbfuH3IogJBEsmNMkUJMWP/v
                Ez2xhKKRwQM0tI9Ng+tRwyhOqzQggBB4S2GiDCIEOCfAaKJb+ctUkKMU6EBpr/CA
                tzRCegoQN2ycCCEt1t7enrurJVjr140vtOdEyyR3l9aDdJrtqJTqwlxl+a/8AD2y
                CDc5KCaZIRqabMEscZAx+uN+ZH9sH3qJeMzXqSFl+weGzmFZirGAZHepw1P6gR1E
                600aM+wY723RNAPiBt5+iDyA6X2zfIeLmbweg9aZ5jQ4VgYsq2hlleyu7WP2SDhn
                kVH0c5EJ5vSQhx2RYXZ/JT+MEkAwskYOhDChEfDIrWKGGRAKapajMba2khjJ6Qov
                tEU/vkxFIC1cgMS4hNKXtEIJ2j5em2nMUmDnvjy3bh/tEF7KpXzDnczZFub06xrn
                2YnDPdXWJ9E/fvYeaWEJ6gGOv+Lw1Qih3UMbtxBiT/L9EU8C7zeX/Qx64ElxE6ME
                A3VBywlP6jRXmqfpn+gIvzXdZWunK3riSuhgSChRk8gzotFPLxyde29udUhXgYIf
                cKevdAhspH1G4/gR6W4IkMUr/ur1vRUcRirMxQzzPkCS0qQyUTSS5fSO63bt0O8D
                jhr49rPSLAxKI0av8DY0Fg4CLhPXQy06mYLg5Ju5n/Az0outePcbArXxK0csiEwS
                v/qKPn7aa378Bq3SBTEAkS8U4le1n3bM6vpz7wPXTiuDogsEboDXVH9bvhxyC3bL
                jUjbdmJnn9t4igp4/IO9St610QRy7582+DauSaLMFjLQyq+/YxBWdgjVX0wvqrPc
                0hHKZbI5v4nF5rcPPA0tT1PaA3kZLpksJ5NqMtHA5+Mrq8jZvbc2UG2Gg0RmaP02
                VU4PMzUkj/F4ft4D/gnbg0q+kIfpWKTkuzDa6ppi+ZfMeG9Z/TQkaA1n3vC4pluf
                Yy0GCaxSz5m/Mz9jYODfaxXRPaOFhKB45D3hh7HHy8kW5nICkMxKiTvObrOIXxM/
                BAvEdKEIsAJ2LROmtsiesZG2t8pnpwn0ChVqpR4sLy18MAbxwkxKGccmWiR1dpt9
                jV25p7YpfyLfC3uEJFfWuy3SHNys0ctXqxIUamZJz/MXDOvnW1Lia3B+AEHYDSdC
                25iN/2jk4BpOdQ6c8fHYwRZUXlDx/JlVZZIrK55l5jzWpogTkiaz0gApMnbw7GZt
                tEIEsQYjBvZBcr3J2PcP4QnbqDQ32J162fddF2gx65yeCV7AFORfpUdF4bkTbBqr
                4h7BCLus4RyWskfQY0FcICIxtyVLNKGD0ft4fZKf+QSdLbX3z9IEuvGttZauutIu
                GQIDAQABo4GlMIGiMB0GA1UdDgQWBBQ+vQlxZlCPynROv/rzvaKOH0Kv8zAPBgNV
                HRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIB9jBgBgNVHSUBAf8EVjBUBggrBgEF
                BQcDAQYIKwYBBQUHAwIGCCsGAQUFBwMDBggrBgEFBQcDBAYIKwYBBQUHAwgGCCsG
                AQUFBwMJBgorBgEEAYI3CgMBBgorBgEEAYI3CgMEMA0GCSqGSIb3DQEBCwUAA4IE
                AQAg+OG1iQRjK48W08KsTIUWqVHwnR3cKbSNgicdYqxPm98xJx/Fa5a/lOZB2p8f
                5FJRJ3X07SMogtbjtyQJtlxKxE8x4rPg1pYyUf1m8AEne2Hpq7doXwQfby45rfx9
                O3xpRg/iRFnweOCdeikwppaCHquBJZrS2Zjfh7mI51ql96OqXTlvkTk9fHvwXukR
                3lX0OSf0Fe6mz7Duu2Vs8qYDEvAapWfuliRa+htBInoyMBIbNBbWCA4rlXpSsrX/
                FaIW5gCl/0n1ZJ71XQOomuqn6wxUqDqK9xXy0q0mz+mlgt9yKqfrgMWNprn20rts
                UYPKmYtDpspjV5ufFFvzG56xbqwHxqrkiFSQGdA1sy6fZpMkosNV3lUfIuSXUVk2
                ClXW5RufE9pR9TVWAo+krkYsus4TG9Dfz07dFQJwjrABkORRJcKVfeAem9Z1nsCH
                g0W+25lKWr9FCGW5staiIjaHml1utPtx16o5I+rwVE4FRMSkeBRLKasaffUVuavM
                0SeqYytrQGBiacWsFehggU5+yXCluojjUL/bo1KfS9XoANZj8qKRLHRQNQdwz2Ec
                SSRSnDGgzNeVkADTfQxJ07MwRd9PAfex0Qp/WVtijtuEZ467Jf2F1d6BjhHjobPG
                nm6uOIu9RWBbKauPz+4EDQcXrcdWIFP471jpgNqx7I3Yh7O0ZhwEP6QCKt4zg2Ej
                fbq1QiKv0cGB0/TA+IEvbfao+JS1k/EtM0ll1e5XfalDb0An+/N4yp8/3DNGOuIo
                pE8lWM/SPVi0uj2k5tyredmCW+T0TvHo/8r05ZOLPOJkeBWh32eoKBbLXkQtG7AD
                MGNLXDjXaYFCsd0o09MMk94D0zfS4ovAfVQ5Q0gnBzc7J1gCNPWRd2Dw7qkDVhqn
                sXZIbg/cIS5cfV/6sUSgbrV8Nv+o61OvKw7Cc+8l+Ix9S5AO94heQZDZbWNpN7Yu
                6l9eDUUjQBtgDweZzQILX3yj4juEbK2GG1wzgoqOm9c7MBv9vrWvKYL5RB3pN4jb
                ThIDFaIVJtvnM1oKpo6GsMiZTnMhUWiUN95k1P+W5NFwz4/xBiu1IWys+aP4hPHj
                MqW4oSR/Nh8C3Qiuwmg7fKN2ZbiQh0AHUIu6Wk6hkiaq2L+Dxj+0LVWon7GXb9vB
                dDL17HGTLwUbeM1mrLm9x7OUdE1fZTHfgpehuPmQ7SuYbBhUO8voZrd4S2yhgWoD
                qHPRu5yW1GxE2Wz72psg1kYLUmt69dj4DQol1j/Isir08K/RiD/9EWEBvwTuU/cd
                uIg3Q/1rd9jFTdRM3vVZSb2a470gc/HX2e1kL35YjWVRtSbj912GHpo8pD6dL2u0
                q0CLZ9HY0pf+7WsqnBgiwIRo
                -----END CERTIFICATE-----
