---
server:
    servlet:
        context-path: /
spring:
    application:
        name: bastet
    profiles:
        active: dev
    main:
        lazy-initialization: true
bastet:
    auth:
        filter:
            header-key: Authorization
        security-config:
            root-username: root
            root-password: root
    physical:
        type: postgres
        config:
            url: jdbc:postgresql://localhost:5432/bastet
            properties:
                user: bastet
                password: bastet
                driver-class-name: org.postgresql.Driver