server:
  port: 8081
  servlet:
    context-path: /
debug: true
spring:
  profiles:
    active: default
  application:
    name: minerva
  sql:
    init:
      mode: always
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
minerva:
  keyvalue:
    encrypt: false
    encryption-key: "1234567890123456"
