---
server:
    servlet:
        context-path: /
spring:
    devtools:
        livereload:
            enabled: false
        restart:
            enabled: false
    profiles:
        active: dev
    application:
        name: minerva
    main:
        lazy-initialization: false
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
    #        url: jdbc:sqlite:mydatabase.db
    #        driver-class-name: org.sqlite.JDBC
    jpa:
        show-sql: true
        # database-platform: org.hibernate.community.dialect.SQLiteDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
