---
name: Release
"on":
    push:
        branches:
            - main

jobs:
    release:
        permissions:
            contents: write
            issues: write
            pull-requests: write
            id-token: write
        name: release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Import GPG key
              id: import-gpg
              uses: crazy-max/ghaction-import-gpg@v6
              with:
                  gpg_private_key: ${{ secrets.ARPANREC_GITHUB_ACTIONS_GPG_PRIVATE_KEY }}
                  passphrase: ${{ secrets.ARPANREC_GITHUB_ACTIONS_GPG_PRIVATE_KEY_PASSPHRASE }}
                  git_user_signingkey: true
                  git_commit_gpgsign: true
                  trust_level: 5

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  cache-dependency-path: .github/files/package-lock.json

            - name: Setup JDK 17
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: 17
                  cache: gradle

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3
              with:
                  gradle-version: 8.5

            - name: Build with Gradle
              run: gradle bootJar

            - name: Install node dependencies
              run: |+
                  npm i semantic-release@23.0.0 \
                    @semantic-release/commit-analyzer@11.1.0 \
                    @semantic-release/release-notes-generator@12.1.0 \
                    @semantic-release/changelog@6.0.3 \
                    @semantic-release/exec@6.0.3 \
                    @semantic-release/git@10.0.1 \
                    @semantic-release/github@9.2.6 -D

            - name: Release
              run: |+
                  git config --global user.email "${{ steps.import-gpg.outputs.email }}"
                  git config --global user.name "${{ steps.import-gpg.outputs.name }}"
                  npx semantic-release@23.0.0 --extends ./.github/files/release.config.js
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GIT_AUTHOR_NAME: "${{ steps.import-gpg.outputs.name }}"
                  GIT_AUTHOR_EMAIL: "${{ steps.import-gpg.outputs.email }}"
                  GIT_COMMITTER_NAME: "${{ steps.import-gpg.outputs.name }}"
                  GIT_COMMITTER_EMAIL: "${{ steps.import-gpg.outputs.email }}"
