---
name: Gradle Test

on:
    push:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup JDK 21
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: 21
                  cache: gradle

            - name: Build with Gradle
              run: ./gradle test
